mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('trivia.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

trivia/urls.py
from django.urls import path

from . import views

app_name = 'trivia'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('games/', views.GameIndexView.as_view(), name='games'),
    path('games/<int:pk>/', views.GameDetailView.as_view(), name='game_detail'),
    path('games/round/<int:pk>/', views.RoundDetailView.as_view(), name='round_detail'),
    path('games/round/<int:pk>/status/', views.RoundStatusUpdate.as_view(), name='round_update'),
    path('games/<int:game>/answer/<int:round>/<int:question>/', views.response_view, name='new_answer'),
    path('games/<int:game>/wager/', views.finalwager, name='final_wager'),
    path('games/wager/<int:pk>/update/', views.FinalRoundWagerUpdate.as_view(), name='final_wager_update'),
    path('games/<int:game>/final/', views.finalanswer, name='final_answer'),
    path('games/final/<int:pk>/update/', views.FinalAnswerUpdate.as_view(), name='final_answer_update'),
    path('games/<int:game>/final/check/', views.manage_finalanswers, name='check_finalanswer'),
    path('games/<int:game>/check/<int:round>/<int:player>/', views.check_answers, name='check_answers'),
    path('games/finalroundstatus/<int:pk>/', views.FinalRoundStatusUpdate.as_view(), name='finalround_update'),
    path('games/review/<int:pk>/', views.RoundReviewDetail.as_view(), name='round_review'),
    path('games/double/<int:game>/', views.doubleround_view, name='double_round'),
    path('games/double/<int:pk>/update/', views.DoubleRoundUpdate.as_view(), name='double_update'),
    path('manage/', views.ManageView.as_view(), name='manage'),
    path('manage/round/new/', views.RoundCreate.as_view(), name='new_round'),
    path('manage/round/<int:round_pk>/', views.manage_questions, name='manage_questions'),
    path('signup/', views.signup, name='signup'),
]

trivia/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Sum
from django.urls import reverse

# Create your models here.

class Game(models.Model):
    player = models.ManyToManyField(settings.AUTH_USER_MODEL)
    game_title = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    completed = models.BooleanField(default=False)

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.game_title

    def round_status_sum(self):
        return sum([int(x.status) for x in self.round_set.all()])
    
    def score_rounds(self):
        # score the rounds (separated out for final wager clarity)
        dict = {}
        for player in self.player.all():
            dict[player] = {}
            for round in self.round_set.all():
                score = round.score_round()
                dict[player].update(score[player])
            dict[player].update({'total': sum(dict[player].values())})
        return dict

    def score_game(self):
        # total game score
        dict = self.score_rounds()
        for player in self.player.all():
            # delete the old total score for each player from score_rounds()
            del dict[player]['total']
            for round in self.finalround_set.all():
                dict[player].update(round.score_finalround()[player])
            dict[player].update({'total': sum(dict[player].values())})
        return dict


class BaseRound(models.Model):
    STATUS_CHOICES = [
        ('0', 'Not Open'),
        ('1', 'Answer Time'),
        ('2', 'Check Answers'),
        ('3', 'Closed'),
    ]
    category = models.CharField(max_length=100)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=0)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse('trivia:game_detail', kwargs={'pk': self.game_id})

    class Meta:
        abstract = True


class BaseQuestion(models.Model):
    question = models.CharField(max_length=250)
    answer = models.CharField(max_length=150)
    alt_answers = models.CharField(max_length=500, null=True)
    points = models.IntegerField(default=2)

    def __str__(self):
        return self.question

    def answer_set(self):
        if self.alt_answers == None:
            return [self.answer.strip().lower()]
        else:
            alts = [x.strip().lower() for x in self.alt_answers.split(',')]
            return [self.answer.strip().lower()] + alts

    class Meta:
        abstract = True


class BaseResponse(models.Model):
    correct = models.BooleanField(default=False)
    response = models.CharField(max_length=150)
    player = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.response

    class Meta:
        abstract = True


class Round(BaseRound):
    def score_round(self):
        dict = {}
        for player in self.game.player.all():
            score = 0
            for question in self.question_set.filter(round=self):
                for response in question.response_set.filter(player=player):
                    score += response.score_response()
            dict[player] = {self: score}
        return dict

    def check_round(self):
        for question in self.question_set.all():
            for response in question.response_set.all():
                response.check_response()

    def save(self, *args, **kwargs):
        if self.status == '2':
            self.check_round()
        super().save(*args, **kwargs) 


class FinalRound(BaseRound, BaseQuestion):
    STATUS_CHOICES = [
        ('0', 'Not Open'),
        ('1', 'Wager'),
        ('2', 'Answer Time'),
        ('3', 'Check Answers'),
        ('4', 'Closed'),
    ]
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=0)
    points = models.IntegerField(default=0)

    def score_finalround(self):
        dict = {}
        for player in self.game.player.all():
            if self.status != '4':
                dict[player] = {self: 0}
            else:
                try:
                    final_response = FinalResponse.objects.get(player=player, final_round__game=self.game)   
                    if final_response.correct:
                        dict[player] = {self: final_response.wager}
                    else:
                        dict[player] = {self: -final_response.wager}
                except FinalResponse.DoesNotExist:
                    dict[player] = {self: 0}
        return dict

    class Meta:
        constraints = [models.UniqueConstraint(fields=['game'], name='one_final_round')]


class Question(BaseQuestion):
    round = models.ForeignKey(Round, on_delete=models.CASCADE)


class Response(BaseResponse):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('trivia:round_detail', kwargs={'pk': self.question.round_id})

    def check_response(self):
        if self.response.strip() in self.question.answer_set():
            self.correct = True
            self.save()

    def score_response(self):
        if self.correct:
            try:
                double_round = self.question.round.doubleround_set.get(player=self.player)
                multiplier = double_round.multiplier
                score = self.question.points * multiplier
            except DoubleRound.DoesNotExist:
                score = self.question.points
            return score
        else:
            return 0

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['player', 'question'], name='unique_answer')
        ]


class FinalResponse(BaseResponse):
    wager = models.IntegerField(default=None, null=True)
    final_round = models.ForeignKey(FinalRound, on_delete=models.CASCADE)

    def clean(self):
        max_wager = self.final_round.points
        game = self.final_round.game
        score = game.score_rounds()[self.player]['total']
        if max_wager > 0 and self.wager > max_wager:
            raise ValidationError(f'Above max wager. Max wager is {max_wager}.')
        elif max_wager == 0 and self.wager > score:
            raise ValidationError(f'Your max wager is your score. You have {score}.')

    def get_absolute_url(self):
        return reverse('trivia:game_detail', kwargs={'pk': self.final_round.game.id})

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['final_round', 'player'], name='one_final_answer')
        ]


class DoubleRound(models.Model):
    player = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    round = models.ForeignKey(Round, on_delete=models.CASCADE, null=True)
    multiplier = models.IntegerField(default=2)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['player', 'game'], name='unique_double_round')
        ]

    def __str__(self):
        return self.round

    def get_absolute_url(self):
        return reverse('trivia:game_detail', kwargs={'pk': self.game_id})

trivia/forms.py
from django.forms import ModelForm

from .models import DoubleRound, FinalResponse, Response


class ResponseForm(ModelForm):
    class Meta:
        model = Response
        fields = ['response']


class FinalResponseForm(ModelForm):
    class Meta:
        model = FinalResponse
        fields = [
            'final_round',
            'player'
        ]

trivia/templates/trivia/check_answers.html
{% extends 'base_site.html' %}

{% block title %}Check Answers{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; <a href="{% url 'trivia:games' %}">Game List</a>
{% if responses %}
{% with responses|first as response %}
&rsaquo; <a href="{% url 'trivia:game_detail' response.question.round.game.id %}">{{ response.question.round.game }}</a>
&rsaquo; {{ response.question.round }}
{% endwith %}
{% endif %}
</div>
{% endblock %}

{% block content %}

<h1>{% firstof player.get_short_name player.get_username %}'s Answers</h1>

<form method="post">
{% csrf_token %}
<table>
    <thead>
        <tr>
            <th>Question</th>
            <th>Answer</th>
            <th>Points</th>
            <th>{% firstof player.get_short_name player.get_username %}'s Response</th>
            <th>Correct</th>
        </tr>
    </thead>
    <tbody>
    {{ formset.management_form }}
    {% for form in formset %}
        {{ form.id }}
        <tr>
            {% for r in responses %}
            {% if r.id == form.id.value %}
            <td>{{ r.question.question }}</td>
            <td>{{ r.question.answer }}</td>
            <td>{{ r.question.points }}</td>
            <td>{{ r }}</td>
            {% endif %}
            {% endfor %}
            <td>{{ form.correct }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<br/>
<input type="submit" value="Submit">
</form>

{% endblock %}

trivia/templates/trivia/doubleround_form.html
{% extends 'base_site.html' %}

{% block title %}Choose a Double Round{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; <a href="{% url 'trivia:games' %}">Game List</a>
{% if object %}
&rsaquo; <a href="{% url 'trivia:game_detail' object.game_id %}">{{ object.game }}</a>
{% endif %}
</div>
{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

trivia/templates/trivia/final_answer.html
{% extends "base_site.html" %}

{% block title %}Final Answer!{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; <a href="{% url 'trivia:games' %}">Game List</a>
&rsaquo; <a href="{% url 'trivia:game_detail' finalresponse.final_round.game.id %}">{{ finalresponse.final_round.game }}</a>
&rsaquo; {{ finalresponse.final_round }} &rsaquo; Final Answer
</div>
{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    Question:
    <strong>
    {{ finalresponse.final_round.question }}
    </strong><br>
    {{ form }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

trivia/templates/trivia/finalanswer_check.html
{% extends 'base_site.html' %}

{% block title %}Final Answer Check{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; <a href="{% url 'trivia:games' %}">Game List</a>
&rsaquo; <a href="{% url 'trivia:game_detail' game %}">
    {% with final_answers|first as final %}
    {{ final.final_round.game }}
    {% endwith %}
</a>
&rsaquo; Final Answer Check
</div>
{% endblock %}

{% block content %}

<p>{{ final_answers.first.final_round.question }}</p>
<strong>
<p>{{ final_answers.first.final_round.answer }}</p>
</strong>

<form method="post">
    {% csrf_token %}
    <table>
        <thead>
            <th>Player</th>
            <th>Answer</th>
            <th>Correct?</th>
        </thead>
        <tbody>
            {{ formset.management_form }}
            {% for form in formset %}
                {{ form.id }}
                <tr>
                    {% for a in final_answers %}
                    {% if a.id == form.instance.id %}
                    <td>{{ a.player }}</td>
                    <td>{{ a.response }}</td>
                    {% endif %}
                    {% endfor %}
                    <td>{{ form.correct }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    <input type="submit" value="Submit">
</form>

{% endblock %}

trivia/templates/trivia/finalround_form.html
{% extends 'base_site.html' %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; <a href="{% url 'trivia:games' %}">Game List</a>
&rsaquo; <a href="{% url 'trivia:game_detail' 1 %}">{{ final_round.game }}</a>
&rsaquo; Round Status
</div>
{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

trivia/templates/trivia/game_detail.html
{% extends 'base_site.html' %}

{% block title %}{{ game }} | Game Detail{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; <a href="{% url 'trivia:games' %}">Game List</a>
&rsaquo; {{ game }}
</div>
{% endblock %}

{% block content %}

<h1>{{ game }}</h1>
{% if game.round_status_sum == 0 %}
<a href="{% url 'trivia:double_round' game.id %}">
<input type="submit" value="Choose a Round to Double" />
</a>
{% endif %}
{% if game.round_set.all %}
<table border cellpadding=10>
    <thead>
        <tr>
            <th>Round Name</th>
            {% for round in game.round_set.all %}
                <th>
                    <a href="{% url 'trivia:round_review' round.id %}">{{ round }}</a>
                </th>
            {% endfor %}
            {% if game.finalround_set.all %}
            {% for f in game.finalround_set.all %}
            {% if f.status == '0' %}
            <th>Final Round</th>
            {% else %}
            <th>{{ f.category }}</th>
            {% endif %}
            {% endfor %}
            {% endif %}
            <th>Total Score</th>
        </tr>
        <tr>
            <th>Status</th>
            {% for round in game.round_set.all %}
            <th><a
                {% if request.user.is_staff %}
                href="{% url 'trivia:round_update' round.id %}"
                {% endif %}
                >{{ round.get_status_display }}</a></th>
            {% endfor %}
            {% for r in game.finalround_set.all %}
            <th><a
                {% if request.user.is_staff %}
                href="{% url 'trivia:finalround_update' r.id %}"
                {% endif %}
                >{{ r.get_status_display }}</a></th>
            {% endfor %}
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for k, v in game.score_game.items %}
        <tr>
            <td>{{ k }}</td>
            {% for a, b in v.items %}
            <td>
                {% for round in a.doubleround_set.all %}
                {% if round.player == k %}
                <strong>
                {% endif %}
                {% endfor %}
                    {% if a != 'total' %}
                    <a href="{% url 'trivia:check_answers' game=game.id round=a.id player=k.id %}">
                    {% endif %}
                    {{ b }}
                    </a>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
        <tr>
            <td></td>
                {% for round in game.round_set.all %}
                <td>
                {% if round.get_status_display == 'Answer Time' %}
                <a href="{% url 'trivia:round_detail' round.id %}">
                    <input type="submit" value="Answer" />
                </a>
                {% elif round.get_status_display == 'Closed' %}
                <a href="{% url 'trivia:round_review' round.id %}">
                    <input type="submit" value="Review" />
                </a>
                {% endif %}
                </td>
                {% endfor %}
                {% for r in game.finalround_set.all %}
                <td>
                    {% if r.status == '1' %}
                    <a href="{% url 'trivia:final_wager' game.id %}">
                        <input type="submit" value="Wager" />
                    </a>
                    {% elif r.status == '2' %}
                    <a href="{% url 'trivia:final_answer' game.id %}">
                        <input type="submit" value="Answer" />
                    </a>
                    {% elif r.status == '3' %}
                    <a href="{% url 'trivia:check_finalanswer' game.id %}">
                        <input type="submit" value="Check" />
                    </a>
                    {% endif %}
                </td>
                {% endfor %}
        </tr>
    </tbody>
</table>
{% else %}
    <p>Game details are not available.</p>
{% endif %}
<h3>Notes</h3>
<p>*Choose a round to double before the game starts.</p>
<p>*The bold numbered round is the player's double round.</p>
<p>*Click on another player's score to check their answers.</p>

{% endblock %}

trivia/templates/trivia/game_list.html
{% extends 'base_site.html' %}

{% block title %}Trivia! | Game List{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; Game List
</div>
{% endblock %}

{% block content %}

<h1>List of Recent Games</h1>
{% if game_list %}
<table>
    <tr>
        <th>Game Name</th>
        <th>Publish Date</th>
    </tr>
    {% for game in game_list %}
    <tr>
        <td><a href="{% url 'trivia:game_detail' game.id %}">{{ game.game_title }}</a></td>
        <td>{{ game.pub_date }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
    <p>No games are available.</p>
{% endif %}

{% endblock %}

trivia/templates/trivia/index.html
{% extends 'base_site.html' %}

{% block title %}Trivia!{% endblock %}

{% block content %}

<h1>Welcome to Trivia!</h1>
<p>See <a href="{% url 'trivia:games' %}">available games</a></p>

{% if not user.is_authenticated %}
<p>Please <a href="{% url 'login' %}">sign in</a> if you are a returning player.</p>
<p>Please <a href="{% url 'trivia:signup' %}">create an account</a> if you're here for the first time.</p>
{% endif %}
{% if user.is_staff %}
<p>If you have permission, <a href="{% url 'trivia:manage' %}">go to manage games.</a></p>
{% endif %}

{% endblock %}

trivia/templates/trivia/manage.html
{% extends 'base_site.html' %}

{% block title %}Manage{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; Manage
</div>
{% endblock %}

{% block content %}

<p>Create new game:</p>
<input type="submit" value="Coming Soon">
<p>Create a new round:</p>
<a href="{% url 'trivia:new_round' %}">
<input type="submit" value="Create New Round with Questions">
</a>

{% endblock %}

trivia/templates/trivia/manage_questions.html
{% extends 'base_site.html' %}

{% block title %}Manage Questions{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; <a href="{% url 'trivia:manage' %}">Manage</a>
&rsaquo; Questions
</div>
{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    <table>
        <thead>
            <tr>
                <th>Question</th>
                <th>Answer</th>
            </tr>
        </thead>
        <tbody>
        {% for form in formset %}
            {{ form.id }}
            <tr>
                <td>{{ form.question }}</td>
                <td>{{ form.answer }}</td>
                <td>{{ form.alt_answers }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <input type="submit" value="Submit">
</form>

{% endblock %}

trivia/templates/trivia/response.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Submit">
</form>

trivia/templates/trivia/roundresponse_form.html
{% extends "base_site.html" %}

{% block title %}Answer Time{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; <a href="{% url 'trivia:games' %}">Game List</a>
&rsaquo; <a href="{% url 'trivia:game_detail' round.game.id %}">{{ round.game }}</a>
&rsaquo; <a href="{% url 'trivia:round_detail' round.id %}">{{ round }}</a>
</div>
{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <table>
        <th>Question</th><th>Response</th>
    {% for x, y in items %}
        <tr><td>{{ x }}</td><td>{{ y }}</td></tr>
    {% endfor %}
    </table>
    <input type="submit" value="Submit">
</form>

{% endblock %}

trivia/templates/trivia/signup.html
{% extends 'base_site.html' %}

{% block title %}Trivia! | Signup{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <input type="submit" value="Sign Up" />
  </form>
{% endblock %}

trivia/templates/trivia/wager_form.html
{% extends "base_site.html" %}

{% block title %}Wager Time{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'trivia:index' %}">Home</a>
&rsaquo; <a href="{% url 'trivia:games' %}">Game List</a>
&rsaquo; <a href="{% url 'trivia:game_detail' finalresponse.final_round.game.id %}">{{ finalresponse.final_round.game }}</a>
&rsaquo; Wager
</div>
{% endblock %}

{% block content %}

<h2>Category: {{ finalresponse.final_round }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}